spring.application.name=VoltExchange
spring.profiles.active=dev

# DB configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Jpa Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Auth configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=900000
refreshtoken.expiration=604800

