spring.application.name=VoltExchange
spring.profiles.active=dev
# DB configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Jpa Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Auth configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration.milliseconds=${JWT_EXPIRATION:900000}
refreshtoken.expiration.seconds=${REFRESH_EXPIRATION:604800}

# redis configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.cache.type=redis

# rate limiting configuration
rate.limit.transfer.capacity=${TRANSFER_TOKEN_CAPACITY}
rate.limit.transfer.refill.minutes=${TRANSFER_REFILL_TIME}


